// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRegex(arg1, arg2) {
  return window['go']['scan']['Scan']['AddRegex'](arg1, arg2);
}

export function ChangeRegexStatus(arg1) {
  return window['go']['scan']['Scan']['ChangeRegexStatus'](arg1);
}

export function DelRegex(arg1) {
  return window['go']['scan']['Scan']['DelRegex'](arg1);
}

export function DisableAllRegex() {
  return window['go']['scan']['Scan']['DisableAllRegex']();
}

export function EnableAllRegex() {
  return window['go']['scan']['Scan']['EnableAllRegex']();
}

export function FindSensitiveInfo(arg1) {
  return window['go']['scan']['Scan']['FindSensitiveInfo'](arg1);
}

export function GetRegx() {
  return window['go']['scan']['Scan']['GetRegx']();
}

export function Init() {
  return window['go']['scan']['Scan']['Init']();
}

export function SaveRegex() {
  return window['go']['scan']['Scan']['SaveRegex']();
}

export function SaveResult(arg1) {
  return window['go']['scan']['Scan']['SaveResult'](arg1);
}

export function ScanSensitive(arg1, arg2) {
  return window['go']['scan']['Scan']['ScanSensitive'](arg1, arg2);
}

export function StopScan() {
  return window['go']['scan']['Scan']['StopScan']();
}

export function UpdateRegex(arg1, arg2, arg3) {
  return window['go']['scan']['Scan']['UpdateRegex'](arg1, arg2, arg3);
}
