// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFileList(arg1) {
  return window['go']['crack']['Crack']['GetFileList'](arg1);
}

export function Unpack(arg1, arg2, arg3) {
  return window['go']['crack']['Crack']['Unpack'](arg1, arg2, arg3);
}

export function WailsInit(arg1) {
  return window['go']['crack']['Crack']['WailsInit'](arg1);
}
