// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {runtime} from '../models';

export function GetFileList(arg1:string):Promise<model.Response>;

export function Unpack(arg1:string,arg2:string,arg3:string):Promise<model.Response>;

export function WailsInit(arg1:runtime.Runtime):Promise<void>;
