// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';

export function Unpack(arg1:string,arg2:string,arg3:string):Promise<string>;

export function WailsInit(arg1:runtime.Runtime):Promise<void>;
