// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDecDir(arg1) {
  return window['go']['main']['App']['OpenDecDir'](arg1);
}

export function OpenDir() {
  return window['go']['main']['App']['OpenDir']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function WailsInit(arg1) {
  return window['go']['main']['App']['WailsInit'](arg1);
}
