// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';

export function OpenDecDir(arg1:string):Promise<void>;

export function OpenDir():Promise<string>;

export function OpenFile(arg1:string):Promise<string>;

export function WailsInit(arg1:runtime.Runtime):Promise<void>;
