// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GetDefaultOutPath():Promise<string>;

export function OpenDecDir(arg1:string):Promise<string>;

export function OpenDir():Promise<string>;

export function OpenDisFile(arg1:string):Promise<model.Response>;

export function OpenScanDir(arg1:string):Promise<string>;

export function OpenWxPackDir(arg1:string):Promise<string>;

export function SelectOpenFile():Promise<model.Response>;
